import type { Metadata } from "next";
import { Fugaz_One, Poppins } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";

const fugazOne = Fugaz_One({
  variable: "--font-fugazone",
  subsets: ["latin"],
  weight: "400",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${fugazOne.variable} ${poppins.variable}  antialiased`}
      >
        <Navbar />
        <div className="font-poppins">
          {children}
        </div>
      </body>
    </html>
  );
}
